apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: partition
  namespace: flux-system
spec:
  targetNamespace: osdu
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./software/charts/osdu-spi-service
      sourceRef:
        kind: GitRepository
        name: osdu-spi-stack-system
  values:
    image:
      repository: community.opengroup.org:5555/osdu/platform/system/partition/partition-master
      tag: "a57c4725b5923cfc9d9f8e6fd418b299ca79350d"
    redisTls: true
    nodeSelector:
      agentpool: osdu
    tolerations:
      - key: workload
        operator: Equal
        value: "osdu"
        effect: NoSchedule
    env:
      - name: SPRING_APPLICATION_NAME
        value: partition
      - name: SERVER_SERVLET_CONTEXTPATH
        value: /api/partition/v1/
      - name: ACCEPT_HTTP
        value: "true"
      - name: AZURE_ISTIOAUTH_ENABLED
        value: "true"
      - name: AZURE_PAAS_WORKLOADIDENTITY_ISENABLED
        value: "true"
      - name: REDIS_DATABASE
        value: "1"
      - name: PARTITION_SPRING_LOGGING_LEVEL
        value: DEBUG
